# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Rojak' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Rojak
  pod 'Alamofire', '~> 4.0'
  pod 'AlamofireImage', '~> 3.1'
  pod 'SwiftyJSON'

  target 'RojakTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RojakUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
