-- TODO: solve masalah kalau ada error di tengah2 statement
--       untuk saat ini solusinya buat duplicate versi sebelumnya
--       lalu run against it, sampe bener2 gak ada error
--       NOTE: we can't use MySQL transaction for data definition

-- Update the sentiment table
-- Drop the existing foreign key
-- The constraint name is generated by MySQL
ALTER TABLE sentiment 
    DROP FOREIGN KEY `sentiment_ibfk_1`;
ALTER TABLE sentiment
    DROP COLUMN `candidate_id`;
-- Create new foreign key
ALTER TABLE sentiment
    ADD COLUMN `pair_of_candidates_id`
    int(10) unsigned;
ALTER TABLE sentiment
    ADD CONSTRAINT `fk_sentiment_pair_of_candidates_id`
    FOREIGN KEY (`pair_of_candidates_id`)
    REFERENCES pair_of_candidates(`id`)
    ON DELETE CASCADE;

-- Update the news_sentiment table
ALTER TABLE news_sentiment
    DROP COLUMN `score`;
ALTER TABLE news_sentiment
    ADD COLUMN `confident_score_raw`
    double NOT NULL;
ALTER TABLE news_sentiment
    ADD COLUMN `confident_score_scaled`
    double NOT NULL;
