# Run this script to create stopwords.py based on stopwords.txt
import json

def generate(input_txt, output_py):
    # Read line by line
    txt_file = open(input_txt)
    words = set([])
    for raw_line in txt_file:
        line = raw_line.strip()
        # Skip empty line
        if len(line) < 1: continue
        # Skip comments
        if line[0] == '#': continue
        # Collect the stopwords
        words.add(line)

    # Dump the array to a file
    output = open(output_py, 'w')
    output.write('# DO NOT EDIT THIS FILE!\n')
    output.write('# Edit stopwords.txt, generate this file again via ')
    output.write('generate_stopwords.py\n')
    output.write('stopwords = set(%s)' % (json.dumps(sorted(words), 
        indent=4)))
    output.close()
    txt_file.close()

if __name__ == '__main__':
    generate('stopwords.txt', 'stopwords.py')
