#%RAML 0.8
title: Rojak API
version: v1
baseUri: https://api.rojak.com/
mediaType: application/json

/candidates:
  description: List of candidates
  get:
    description: Get list of candidates
  /{candidateId}:
    get:
      description: Get specific candidate information based on their id
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "data": {},
                  "success": true,
                  "status": 200
                }
        404:
          body:
            application/json:
              example: |
                {
                  "data": {},
                  "success": false,
                  "status": 404
                }
    /news:
      get:
        description: Get list of news for this candidate

/news:
  description: List of news on rojak api
  get:
  /{newsId}:
    get:
      description: Retrieve a specific news
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "data": {
                    "id": 1,
                    "mediaId": 3,
                    "title": "Kunjungan presiden jokowi ke Depok",
                    "content": "<h1>Kunjungan presiden jokowi</h1><p>Jalan jalan ke Depok</p>",
                    "url": "https://rojaktv.com/jokowi-jalan-jalan-ke-depok".
                    "insertedAt": 1341533193,
                    "updatedAt": 1341533193
                  },
                  "success": true,
                  "status": 200
                }
    /mentions:
      get:
    /newsSentiments:
      get:
/media:
  get:
/sentiments:
  get:
