#%RAML 0.8
---
title: Rojak
version: v1
baseUri: https://api.rojak.com/v1
mediaType: application/json

resourceTypes:
  - resource-collection:
      get:
        description: Get a list of <<resourcePathName>>.
        responses:
          200:
            body:
              application/json:
                example: |
                  <<exampleCollection>>
  - resource-collection-item:
      get:
        description: |
          Get the <<resourcePathName|!singularize>>
          with <<resourcePathName|!singularize>>Id =
          {<<resourcePathName|!singularize>>Id}.
        responses:
          200:
            body:
              application/json:
                example: |
                  <<exampleItem>>
          404:
            body:
              application/json:
                example: |
                  { "message" : "<<resourcePathName|!singularize>> not found" }
  - generic-collection:
      get:
        description: <<description>>
        responses:
          200:
            body:
              application/json:
                example: |
                  <<exampleCollection>>
  - generic-item:
      get:
        description: <<description>>
        responses:
          200:
            body:
              application/json:
                example: |
                  <<exampleItem>>
          404:
            body:
              application/json:
                example: |
                  { "message" : "item not found" }

/pairings:
  type:
    resource-collection:
      exampleCollection: !include examples/pairing-list.sample
  /{pairingId}:
    type:
      resource-collection-item:
        exampleItem: !include examples/pairing.sample
    /media-sentiments:
      type:
        generic-collection:
          description: Get a breakdown of media sentiments for this pairing.
          exampleCollection: !include examples/pairing-candidate-sentiments.sample

/candidates:
  type:
    resource-collection:
      exampleCollection: !include examples/candidate-list.sample
  /{candidateId}:
    type:
      resource-collection-item:
        exampleItem: !include examples/candidate.sample
    /media-sentiments:
      type:
        generic-collection:
          description: Get a breakdown of media sentiments for this candidate.
          exampleCollection: !include examples/pairing-candidate-sentiments.sample

/news:
  type:
    resource-collection:
      exampleCollection: !include examples/news-list.sample
  /{newsId}:
    type:
      resource-collection-item:
        exampleItem: !include examples/news.sample

/media:
  type:
    resource-collection:
      exampleCollection: !include examples/media-list.sample
  /{mediaId}:
    type:
      resource-collection-item:
        exampleItem: !include examples/media.sample
    /sentiments:
      type:
        generic-collection:
          description: Get a breakdown of sentiments for each pairing and candidate by this media.
          exampleCollection: !include examples/pairing-candidate-sentiments.sample
